### PR TITLE
Update to latest process.dlopen signature

### PR DESCRIPTION
**Pull request by kevzettler**
addresses: https://github.com/webpack/webpack/issues/1053

### CODE REVIEW

**Comment by jwaldrip** [comment]
Can we get this merged in?

**Comment by joerick** [comment]
+1 this PR fixes my issue - I was getting this error

    Error: dlopen([object Object], 1): image not found

**Comment by israelshirk** [comment]
Lost a couple hours today tracking this down.  It'd be super great to have it in dist.  Thanks!

**Comment by derekstavis** [comment]
Okay, just arrived here. Same problem. Would like to see this one merged and the NPM package updated! 👍

**Comment by marco-amoroso** [comment]
Having the same issue. Same error as `joerick`. This PR fixed it, thanks. Keen for it to be merged, using a fork at the moment.

**Comment by marco-amoroso** [comment]
Update on this, actually I'm using `webpack` and `electron`.

When I open the app locally works (since the node file can be found) but not in other machines, of course. This is the message I get:

`Uncaught Error: Cannot open /Users/marco/web/desktop-app/app/node_modules/keytar/build/Release/keytar.node: Error: The specified module could not be found.
 /Users/marco/web/desktop-app/app/node_modules/keytar/build/Release/keytar.node`

It might be unrelated to this PR, just wanted to flag because I haven't fixed it. Work around for me was to load the Native module from the Main instead of the Renderer.

**Comment by Haraldson** [comment]
Getting the same error as @joerick, trying to use WebChimera in Electron. Will this be merged?

**Comment by joerick** [comment]
All are welcome to use my fork in the meantime - it's just got @kevzettler's fix merged:

    "node-loader": "github:joerick/node-loader",

**Comment by botezatumihaicatalin** [comment]
bump!

**Comment by israelshirk** [comment]
Will trade: Amazon e-gift card for merge.  Thanks, Israel

**Comment by sokra** [comment]
Thanks

**Comment by israelshirk** [comment]
@sokra what is your e-mail for the bounty?

**Comment by sokra** [comment]
oh. give it to @kevzettler he've done the work. I only pushed the button.

I often miss PRs in some projects. Too many projects and mails.

**Comment by israelshirk** [comment]
That's really cool of you @sotra...  Now both of you get me your e-mails, this helps me in a huge way :D

Mine is israel@alpine-digital-research.com

**Comment by israelshirk** [comment]
@kevzettler ^^^^^

**Comment by sokra** [comment]
This loader was never intented to work with webpack. I wonder why this even works. Doesn't it include an absolute path into the bundle?

**Comment by derekstavis** [comment]
@sokra, and also for the ones who might need to use native modules with webpack:

First, there's this thing that loads the appropriate native module. Shim it.

screenshot from 2016-09-14 20-46-19

Use `node-loader` to load the module:

screenshot from 2016-09-14 20-49-40

After webpack is happy, be sure to replace the absolute path directly on the bundle:

screenshot from 2016-09-14 20-52-41

Here we go. Distribute `node` binary with `bundle.min.js` and be happy :+1:

**Comment by kevzettler** [comment]
Woah this was finally merged thanks @sokra 

@israelshirk kevzettler @ gmail com

**Pull request merged**
